/**
 * PDF generation content-integrity tests.
 *
 * The audit's data-loss finding: generatePdf hard-truncated every line at 90
 * characters (no ellipsis, no warning) and never rendered `section.table` at
 * all — while the tool still reported "Created report.pdf". A user could send
 * a client a report with the data tables missing and long lines cut off.
 *
 * pdf-lib produces a real PDF, so we assert on the extractable text of the
 * generated bytes rather than on internal calls.
 */
import { describe, it, expect, afterEach } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as zlib from 'zlib';
import { generatePdf, type AnchoredContent } from './generator';

const llm = { type: 'llm' as const, ref: 'llm', excerpt: '' };

function content(sections: AnchoredContent['sections']): AnchoredContent {
  return { title: 'Q3 Report', titleAnchor: 'a0', sections };
}

const tmpFiles: string[] = [];
function outPath(): string {
  const p = path.join(os.tmpdir(), `artha-pdf-${tmpFiles.length}-${process.pid}.pdf`);
  tmpFiles.push(p);
  return p;
}
afterEach(() => { for (const f of tmpFiles.splice(0)) fs.rmSync(f, { force: true }); });

/** Extract visible text from a pdf-lib PDF. pdf-lib compresses content
 *  streams (FlateDecode) and encodes drawn strings as HEX inside `<…> Tj` —
 *  so we inflate every stream and decode the hex. Enough to prove nothing was
 *  dropped, without a full PDF parser. */
function extractText(file: string): string {
  const buf = fs.readFileSync(file);
  const out: string[] = [];
  const streamTag = Buffer.from('stream');
  const endTag = Buffer.from('endstream');
  for (let i = 0; i < buf.length - 6; i++) {
    if (!buf.slice(i, i + 6).equals(streamTag)) continue;
    let j = i + 6;
    while (buf[j] === 0x0d || buf[j] === 0x0a) j++;
    const end = buf.indexOf(endTag, j);
    if (end < 0) continue;
    let content: string;
    try {
      content = zlib.inflateSync(buf.slice(j, end)).toString('latin1');
    } catch {
      content = buf.slice(j, end).toString('latin1');
    }
    for (const m of content.matchAll(/<([0-9A-Fa-f]+)>\s*Tj/g)) {
      out.push(Buffer.from(m[1], 'hex').toString('latin1'));
    }
    i = end; // skip past this stream
  }
  return out.join(' ');
}

describe('generatePdf preserves content', () => {
  it('does not truncate long lines at 90 characters', async () => {
    const longSentence =
      'This single sentence is deliberately far longer than ninety characters so that the old ' +
      'hard slice at ninety would have silently cut the tail off and lost meaningful content.';
    const p = outPath();
    await generatePdf(content([
      { heading: 'Summary', body: longSentence, anchor: 'a1', provenance: llm },
    ]), p);

    const text = extractText(p);
    // The final words — which lived well past character 90 — must survive.
    expect(text).toMatch(/lost meaningful content/);
  });

  it('renders table sections (previously dropped entirely)', async () => {
    const p = outPath();
    await generatePdf(content([
      {
        heading: 'Revenue',
        body: 'By region.',
        table: {
          headers: ['Region', 'Q3 Revenue'],
          rows: [['West', '$1.2M'], ['East', '$0.9M']],
        },
        anchor: 'a1',
        provenance: llm,
      },
    ]), p);

    const text = extractText(p);
    for (const cell of ['Region', 'Q3 Revenue', 'West', '$1.2M', 'East', '$0.9M']) {
      expect(text, `missing table cell: ${cell}`).toContain(cell);
    }
  });

  it('keeps body, bullets AND a table in the same section', async () => {
    const p = outPath();
    await generatePdf(content([
      {
        heading: 'Details',
        body: 'Overview paragraph.',
        bullets: ['First finding', 'Second finding'],
        table: { headers: ['Metric'], rows: [['Uptime 99.9%']] },
        anchor: 'a1', provenance: llm,
      },
    ]), p);
    const text = extractText(p);
    expect(text).toContain('Overview paragraph');
    expect(text).toContain('First finding');
    expect(text).toContain('Uptime 99.9%');
  });

  it('handles a very long unbreakable token without dropping it', async () => {
    const url = 'https://example.com/' + 'segment/'.repeat(30) + 'end';
    const p = outPath();
    await generatePdf(content([
      { heading: 'Link', body: url, anchor: 'a1', provenance: llm },
    ]), p);
    // The tail of the URL must appear somewhere (wrapped across lines).
    expect(extractText(p)).toContain('end');
  });

  it('produces a valid non-empty PDF file', async () => {
    const p = outPath();
    await generatePdf(content([
      { heading: 'H', body: 'B', anchor: 'a1', provenance: llm },
    ]), p);
    const bytes = fs.readFileSync(p);
    expect(bytes.length).toBeGreaterThan(500);
    expect(bytes.toString('latin1', 0, 5)).toBe('%PDF-');
  });
});
